apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "living-objects.fullname" . }}-config
  labels:
    {{- include "living-objects.labels" . | nindent 4 }}
data:
  APP_ENV: prod
  PORT: "8000"
  ORGANISM_LIMIT: "10000"
  CORS_ORIGINS: "*"

