#!/usr/bin/env python3
"""Write a reproducible v8 primitive-contamination audit artifact."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from evolution.contamination_audit import audit_all_tasks


def _markdown(report: dict[str, object]) -> str:
    tasks = list(report["tasks"])
    lines = [
        "# BEAST v8 Primitive-Contamination Audit",
        "",
        "> This report is generated by terminal/one-operation enumeration and actual initialized-population measurement. A no-match result is not a proof that no short composite solution exists.",
        "",
        "| Task | Status | Direct matches | Baseline best | Perfect initial programs |",
        "|---|---|---:|---:|---:|",
    ]
    for task in tasks:
        baseline = task["baseline"]
        lines.append(
            f"| {task['task_id']} | {task['status']} | {len(task['direct_solution_matches'])} | "
            f"{baseline['best_fitness']:.6f} | {baseline['perfect_programs']} |"
        )
    lines.extend([
        "",
        "## Scope boundary",
        "",
        f"The repository has {report['task_count']} implemented evaluator classes. The guide's {report['unimplemented_planned_domains']} planned domains are not audited because they have no executable evaluator.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default="docs/v8-contamination-audit.json")
    parser.add_argument("--baseline-population-size", type=int, default=500)
    args = parser.parse_args()
    report = audit_all_tasks(baseline_population_size=args.baseline_population_size)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    output.with_suffix(".md").write_text(_markdown(report) + "\n", encoding="utf-8")
    print(json.dumps({"output": str(output), "summary": report["summary"]}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
