"""Post-run local evaluation for the finite 28.9M BEAST-BRAIN attempt.

Generated bytes are treated as untrusted data.  They are never executed or
persisted verbatim; only a digest, size, and controller audit decision are
retained for the evaluation record.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

import torch

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from agnes_brain.controller import resolve_guidance
from agnes_brain.cpu_smoke import DEFAULT_DATASET, display_path, sha256_file
from agnes_brain.train_transformer_28m import _heldout_loss, load_local_checkpoint
from agnes_brain.transformer_28m import ByteTransformer28M, Transformer28MConfig, build_local_data_manifest


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RUN_DIRECTORY = REPOSITORY_ROOT / "reports" / "v14" / "beast-brain-28m-local-attempt-20260819"
EVALUATION_SCHEMA_VERSION = "beast-brain-transformer-local-evaluation-v1"


def greedy_byte_continuation(model: Any, prompt: bytes, *, max_new_bytes: int = 192) -> bytes:
    """Produce a deterministic, bounded continuation without executing or trusting it."""

    if not prompt:
        raise ValueError("prompt must be non-empty")
    if not 1 <= max_new_bytes <= 512:
        raise ValueError("max_new_bytes must be in [1, 512]")
    if len(prompt) > model.config.block_size:
        raise ValueError("prompt exceeds the configured local context")
    generated = bytearray(prompt)
    model.eval()
    with torch.no_grad():
        for _ in range(max_new_bytes):
            window = generated[-model.config.block_size :]
            tokens = torch.tensor([list(window)], dtype=torch.long)
            logits, _ = model(tokens)
            generated.append(int(torch.argmax(logits[0, -1]).item()))
    return bytes(generated)


def evaluate_trained_run(
    run_directory: str | Path = DEFAULT_RUN_DIRECTORY,
    *,
    dataset_path: str | Path = DEFAULT_DATASET,
    profile_name: str = "default",
) -> dict[str, Any]:
    """Verify an existing local run and safely audit one generated continuation."""

    run_directory = Path(run_directory)
    run_path = run_directory / "run.json"
    checkpoint_path = run_directory / "checkpoint-latest.pt"
    evaluation_path = run_directory / "evaluation.json"
    if evaluation_path.exists():
        raise FileExistsError(f"refusing to overwrite local evaluation: {evaluation_path}")
    run = json.loads(run_path.read_text(encoding="utf-8"))
    if run.get("schema_version") != "beast-brain-transformer-local-run-v1":
        raise ValueError("run artifact is not a compatible finite local training record")
    if run["execution_boundary"]["network_calls"] != 0 or run["execution_boundary"]["generated_text_executed"]:
        raise ValueError("run artifact violates the local evaluation boundary")
    manifest, _, holdout_payload = build_local_data_manifest(dataset_path)
    if run["dataset"]["dataset_sha256"] != manifest.dataset_sha256:
        raise ValueError("dataset digest does not match the declared training run")
    checkpoint = load_local_checkpoint(checkpoint_path)
    config = Transformer28MConfig(**checkpoint["model_config"])
    model = ByteTransformer28M(config)
    model.load_state_dict(checkpoint["model_state"])
    recomputed_nll = _heldout_loss(model, holdout_payload, config, int(run["run"]["evaluation_batches"]))
    raw_bytes = greedy_byte_continuation(model, b'{"name":"', max_new_bytes=192)
    raw_text = raw_bytes.decode("utf-8", errors="replace")
    decision = resolve_guidance(raw_text, profile_name=profile_name)
    artifact = {
        "schema_version": EVALUATION_SCHEMA_VERSION,
        "status": "completed_local_post_training_evaluation",
        "input_run": {
            "path": display_path(run_path),
            "sha256": sha256_file(run_path),
            "checkpoint_path": display_path(checkpoint_path),
            "checkpoint_sha256": sha256_file(checkpoint_path),
            "training_final_heldout_nll": run["metrics"]["final_heldout_nll"],
        },
        "recomputed_local_metric": {
            "heldout_nll": recomputed_nll,
            "tolerance_to_training_artifact": 1e-6,
            "matches_training_artifact": abs(recomputed_nll - float(run["metrics"]["final_heldout_nll"])) <= 1e-6,
        },
        "generated_continuation": {
            "bytes": len(raw_bytes),
            "sha256": hashlib.sha256(raw_bytes).hexdigest(),
            "prompt_bytes": len(b'{"name":"'),
            "persisted_raw_text": False,
            "interpretation": "A deterministic untrusted byte continuation for controller-contract testing; it is not a program, primitive, or answer.",
        },
        "controller_decision": decision.audit_record(),
        "execution_boundary": {
            "network_calls": 0,
            "model_weights_downloaded": False,
            "generated_text_executed": False,
            "candidate_program_executed": False,
            "persistent_worker_started": False,
        },
        "claim_boundary": {
            "accepted_guidance_is_benchmark_assistance": False,
            "general_language_capability_claim": False,
            "meaning": "The outcome tests only a frozen controller admission contract after local next-byte training.",
        },
    }
    with evaluation_path.open("x", encoding="utf-8") as handle:
        json.dump(artifact, handle, sort_keys=True, indent=2)
        handle.write("\n")
    evaluation_path.chmod(0o600)
    return artifact


def main() -> None:
    parser = argparse.ArgumentParser(description="Evaluate a finite local 28.9M BEAST-BRAIN training artifact.")
    parser.add_argument("--run-directory", type=Path, default=DEFAULT_RUN_DIRECTORY)
    parser.add_argument("--dataset", type=Path, default=DEFAULT_DATASET)
    parser.add_argument("--profile-name", default="default")
    args = parser.parse_args()
    artifact = evaluate_trained_run(args.run_directory, dataset_path=args.dataset, profile_name=args.profile_name)
    decision = artifact["controller_decision"]
    print(
        f"Local evaluation complete: held-out NLL {artifact['recomputed_local_metric']['heldout_nll']:.6f}; "
        f"untrusted continuation controller decision: {decision['accepted']} ({decision['reason']})."
    )


if __name__ == "__main__":
    main()
