/**
 * Signal Loom v3 design philosophy: the observatory is an evidence console,
 * not a demo. Disconnected state is explicit; every organism, market row,
 * score, and event shown here comes from the authenticated control plane.
 */
import { useEffect, useMemo, useState } from "react";
import type { ReactNode } from "react";
import { Activity, ArrowUpRight, BrainCircuit, Check, ChevronRight, Handshake, History, Orbit, Send, Sparkles, WalletCards } from "lucide-react";

type Tone = "cyan" | "copper" | "chartreuse" | "lavender";
type V3PanelsProps = { generation: number; onEvent?: (text: string, tone?: Tone) => void };
type Listing = { name: string; seller_id: string; price: number; adoption_count: number; effectiveness: number };
type Consciousness = { organism_id: string; phi: number; self_model_accuracy: number; workspace_breadth: number; composite: number };

const API_BASE = (import.meta.env.VITE_API_BASE_URL ?? "").replace(/\/$/, "");
function PanelHeading({ index, kicker, title, icon }: { index: string; kicker: string; title: string; icon: ReactNode }) { return <div className="v2-panel-heading"><div className="v2-index">{index}</div><div><div className="section-kicker">{kicker}</div><h3>{title}</h3></div><span className="v2-heading-icon">{icon}</span></div>; }
function GenerationRuler({ generation }: { generation: number }) { return <div className="generation-ruler compact-ruler" aria-label={`Frontier generation ${generation}`}><span className="generation-ruler-label">FRONTIER / STATE WINDOW</span><div className="generation-ruler-track">{Array.from({ length: 14 }, (_, index) => <i key={index} className={index % 4 === 0 ? "major" : ""} />)}</div><span className="generation-ruler-readout">G{String(generation).padStart(4, "0")}</span></div>; }
function useV3Api(onEvent?: V3PanelsProps["onEvent"]) {
  const [token, setToken] = useState(() => window.sessionStorage.getItem("beast-v3-token") ?? "");
  const [connected, setConnected] = useState(false);
  const [error, setError] = useState("");
  const request = async <T,>(path: string, init: RequestInit = {}): Promise<T> => {
    if (!token) throw new Error("Paste an operator token to connect the control plane.");
    const response = await fetch(`${API_BASE}${path}`, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...(init.headers ?? {}) } });
    if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail ?? `API ${response.status}`);
    setConnected(true);
    return response.json() as Promise<T>;
  };
  const saveToken = (value: string) => { setToken(value); window.sessionStorage.setItem("beast-v3-token", value); setConnected(false); setError(""); };
  const run = async <T,>(action: () => Promise<T>, event?: string, tone: Tone = "cyan") => { try { const value = await action(); if (event) onEvent?.(event, tone); setError(""); return value; } catch (reason) { setError(reason instanceof Error ? reason.message : "Request failed"); return undefined; } };
  return { token, connected, error, request, run, saveToken };
}

function ConnectionBar({ api, generation }: { api: ReturnType<typeof useV3Api>; generation: number }) { return <div className="v3-connection-bar"><div><span className={`v3-connection-dot ${api.connected ? "connected" : ""}`} /><strong>{api.connected ? "CONTROL PLANE CONNECTED" : "CONTROL PLANE DISCONNECTED"}</strong><small>G{String(generation).padStart(4, "0")} / v3 frontier stream</small></div><input aria-label="BEAST v3 operator token" value={api.token} onChange={(event) => api.saveToken(event.target.value)} placeholder="paste operator JWT" type="password" /><code>{API_BASE || "same-origin API"}</code>{api.error && <span className="v3-api-error">{api.error}</span>}</div>; }

function ConsciousnessMeter({ api, onEvent }: { api: ReturnType<typeof useV3Api>; onEvent?: V3PanelsProps["onEvent"] }) { const [id, setId] = useState(""); const [metrics, setMetrics] = useState<Consciousness | null>(null); const measure = async () => { const result = await api.run(() => api.request<Consciousness>(`/v3/consciousness/${encodeURIComponent(id.trim())}`), `awareness measured / ${id}`, "lavender"); if (result) setMetrics(result); }; return <article className="v2-panel v3-frontier-panel"><PanelHeading index="12" kicker="CONSCIOUSNESS METER / PROXY ONLY" title="Measure awareness" icon={<BrainCircuit size={17} />} /><p className="v3-panel-note">Φ, self-model accuracy, and workspace breadth are computable architectural proxies—not claims of sentience.</p><div className="v3-inline-form"><input aria-label="Organism ID" value={id} onChange={(event) => setId(event.target.value)} placeholder="organism id" /><button className="v2-small-action" onClick={measure} disabled={!id.trim()}>Measure <Activity size={13} /></button></div>{metrics ? <div className="v3-metric-stack">{[["PHI / INTEGRATION", metrics.phi], ["SELF-MODEL", metrics.self_model_accuracy], ["GLOBAL WORKSPACE", metrics.workspace_breadth], ["COMPOSITE", metrics.composite]].map(([label, value]) => <div className="v3-meter-row" key={String(label)}><span>{label}</span><strong>{Number(value).toFixed(3)}</strong><i><b style={{ width: `${Number(value) * 100}%` }} /></i></div>)}</div> : <div className="v3-empty-state">Select a live organism to measure.</div>}</article>; }

function StrategyMarket({ api, onEvent }: { api: ReturnType<typeof useV3Api>; onEvent?: V3PanelsProps["onEvent"] }) { const [listings, setListings] = useState<Listing[]>([]); const [buyer, setBuyer] = useState(""); const refresh = async () => { const result = await api.run(() => api.request<{ items: Listing[] }>("/v3/market/listings")); if (result) setListings(result.items); }; useEffect(() => { if (api.token) void refresh(); }, [api.token]); const buy = async (name: string) => { const result = await api.run(() => api.request<{ wallet_balance: number }>(`/v3/market/listings/${encodeURIComponent(name)}/buy`, { method: "POST", body: JSON.stringify({ buyer_id: buyer }) }), `market buy / ${name}`, "copper"); if (result) void refresh(); }; return <article className="v2-panel v3-frontier-panel"><PanelHeading index="13" kicker="STRATEGY MARKET / TOKEN ECONOMY" title="Trade what works" icon={<WalletCards size={17} />} /><div className="v3-market-toolbar"><input aria-label="Buyer organism ID" value={buyer} onChange={(event) => setBuyer(event.target.value)} placeholder="buyer organism id" /><button className="v2-small-action" onClick={refresh}>Refresh <ChevronRight size={13} /></button></div><div className="v3-listing-list">{listings.length ? listings.map((listing) => <div className="v3-listing-row" key={listing.name}><div><strong>{listing.name}</strong><small>{listing.seller_id} / {listing.adoption_count} adoptions</small></div><b>{listing.price.toFixed(1)} LO</b><button className="v2-small-action copper-action" disabled={!buyer} onClick={() => buy(listing.name)}>Buy</button></div>) : <div className="v3-empty-state">No market listings returned.</div>}</div></article>; }

function DiplomacyConsole({ api }: { api: ReturnType<typeof useV3Api> }) { const [payload, setPayload] = useState({ our_ecosystem_id: "", their_ecosystem_id: "", our_offer: "", our_request: "" }); const [proposal, setProposal] = useState<{ proposal_id: string; status: string } | null>(null); const propose = async () => { const result = await api.run(() => api.request<{ proposal_id: string; status: string }>("/v3/diplomacy/proposals", { method: "POST", body: JSON.stringify({ ...payload, our_offer: payload.our_offer.split(",").map((item) => item.trim()).filter(Boolean), our_request: payload.our_request.split(",").map((item) => item.trim()).filter(Boolean) }) }), "diplomatic proposal / escrowed", "copper"); if (result) setProposal(result); }; const accept = async () => { if (!proposal) return; const result = await api.run(() => api.request<{ accepted: boolean }>(`/v3/diplomacy/proposals/${proposal.proposal_id}/accept`, { method: "POST" }), "diplomatic exchange / accepted", "cyan"); if (result) setProposal({ ...proposal, status: result.accepted ? "accepted" : "rejected" }); }; return <article className="v2-panel v3-frontier-panel"><PanelHeading index="14" kicker="DIPLOMACY CONSOLE / ESCROW" title="Negotiate across borders" icon={<Handshake size={17} />} /><div className="v3-form-grid">{([["our_ecosystem_id", "our civilization"], ["their_ecosystem_id", "their civilization"], ["our_offer", "offer names / comma separated"], ["our_request", "request names / comma separated"]] as const).map(([key, placeholder]) => <input key={key} aria-label={placeholder} placeholder={placeholder} value={payload[key]} onChange={(event) => setPayload({ ...payload, [key]: event.target.value })} />)}</div><div className="v3-action-row"><button className="v2-small-action copper-action" onClick={propose}><Send size={13} /> Escrow proposal</button>{proposal && <button className="v2-small-action" onClick={accept}><Check size={13} /> Accept {proposal.proposal_id.slice(0, 8)}</button>}</div>{proposal && <code className="v3-result-line">proposal {proposal.status} / {proposal.proposal_id}</code>}</article>; }

function ArchaeologyPanel({ api }: { api: ReturnType<typeof useV3Api> }) { const [target, setTarget] = useState(""); const [report, setReport] = useState<{ excavated: number; resurrected: number; resurrected_names: string[] } | null>(null); const run = async () => { const result = await api.run(() => api.request<typeof report>("/v3/archaeology/pass", { method: "POST", body: JSON.stringify({ target_id: target, cutoff_generation: 10000 }) }), `archaeology pass / ${target}`, "chartreuse"); if (result) setReport(result); }; return <article className="v2-panel v3-frontier-panel"><PanelHeading index="15" kicker="CIVILIZATION ARCHAEOLOGY / MEMOME" title="Excavate lost knowledge" icon={<History size={17} />} /><p className="v3-panel-note">Scan the durable archive for strategies that went extinct, then evaluate and resurface them into a living target.</p><div className="v3-inline-form"><input aria-label="Archaeology target organism ID" value={target} onChange={(event) => setTarget(event.target.value)} placeholder="target organism id" /><button className="v2-small-action" disabled={!target} onClick={run}>Run pass <Sparkles size={13} /></button></div>{report ? <div className="v3-archaeology-result"><strong>{report.resurrected} resurfaced</strong><span>{report.excavated} extinct records evaluated</span><code>{report.resurrected_names.join(" / ") || "no qualifying strategies"}</code></div> : <div className="v3-empty-state">No excavation pass has been requested.</div>}</article>; }

function CoEvolutionTracker({ api }: { api: ReturnType<typeof useV3Api> }) { const [solver, setSolver] = useState(""); const [history, setHistory] = useState<{ difficulty_series: number[]; benchmark_scores: number[] } | null>(null); const run = async () => { const result = await api.run(() => api.request<typeof history>("/v3/benchmarks/co-evolve", { method: "POST", body: JSON.stringify({ generations: 30, solver_ids: solver ? [solver] : [] }) }), "benchmark arms race / 30 generations", "cyan"); if (result) setHistory(result); }; const points = useMemo(() => (history?.difficulty_series ?? []).map((value, index, values) => `${(index / Math.max(1, values.length - 1)) * 100},${100 - value * 90}`).join(" "), [history]); return <article className="v2-panel v3-frontier-panel"><PanelHeading index="16" kicker="SELF-DIRECTED BENCHMARKS / ARMS RACE" title="Track difficulty rising" icon={<ArrowUpRight size={17} />} /><div className="v3-inline-form"><input aria-label="Solver organism ID" value={solver} onChange={(event) => setSolver(event.target.value)} placeholder="optional solver id" /><button className="v2-small-action" onClick={run}>Co-evolve <Orbit size={13} /></button></div>{history ? <><svg className="v3-coevolution-chart" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Benchmark difficulty curve"><polyline points={points} /></svg><div className="v3-chart-caption"><span>G0 / {history.difficulty_series[0]?.toFixed(2)}</span><strong>G30 / {history.difficulty_series.at(-1)?.toFixed(2)}</strong></div></> : <div className="v3-empty-state">Run a 30-generation challenge arms race.</div>}</article>; }

function QuantumViewer({ api }: { api: ReturnType<typeof useV3Api> }) { const [source, setSource] = useState('{"mutation_rate:0.1": 0.7, "mutation_rate:0.3": 0.3}'); const [measured, setMeasured] = useState<Record<string, unknown> | null>(null); const measure = async () => { try { const amplitudes = JSON.parse(source) as Record<string, number>; const result = await api.run(() => api.request<{ genome: Record<string, unknown> }>("/v3/quantum/measure", { method: "POST", body: JSON.stringify({ amplitudes, seed: Date.now() }) }), "quantum measurement / collapsed phenotype", "lavender"); if (result) setMeasured(result.genome); } catch { /* API error surface is handled by the shared hook; malformed JSON remains local. */ } }; return <article className="v2-panel v3-frontier-panel"><PanelHeading index="17" kicker="QUANTUM-INSPIRED GENOME / CLASSICAL MODEL" title="View uncertainty" icon={<Orbit size={17} />} /><textarea className="v3-quantum-editor" aria-label="Quantum amplitudes JSON" value={source} onChange={(event) => setSource(event.target.value)} spellCheck={false} /><button className="v2-small-action" onClick={measure}>Measure phenotype <Sparkles size={13} /></button>{measured && <div className="v3-quantum-result"><span>COLLAPSED GENOME</span><code>{JSON.stringify(measured)}</code></div>}<div className="v3-quantum-note">Amplitudes are a classical uncertainty model; this is not quantum hardware.</div></article>; }

export default function V3Panels({ generation, onEvent }: V3PanelsProps) { const api = useV3Api(onEvent); return <section className="v2-observatory v3-observatory" id="v3-observatory" aria-label="BEAST v3 observatory panels"><ConnectionBar api={api} generation={generation} /><div className="v2-section-intro"><div><div className="eyebrow"><span className="eyebrow-line" />BEAST v3 / FRONTIER INSTRUMENTS</div><h2>Measure the <em>frontier.</em></h2></div><p>Real control-plane state only. Connect an operator token to inspect awareness proxies, trade strategy, negotiate exchange, recover extinct knowledge, and measure uncertainty.</p></div><GenerationRuler generation={generation} /><div className="v2-panels-grid"><ConsciousnessMeter api={api} onEvent={onEvent} /><StrategyMarket api={api} onEvent={onEvent} /><DiplomacyConsole api={api} /><ArchaeologyPanel api={api} /><CoEvolutionTracker api={api} /><QuantumViewer api={api} /></div></section>; }
